const app=document.getElementById("app");let data,state,chapter,mode,q=0,timer,locked=false;const STORE="WQ_V7";const modes=["PICTURE MATCH","SPELL IT","SCRAMBLE","4-CHOICE","SPEED CHALLENGE"];
const blank=()=>({name:"",gender:"boy",score:0,unlocked:1,chapters:{},mastery:{},last:{screen:"home"}});
async function getSave(){try{return JSON.parse(localStorage.getItem(STORE)||"null")}catch(e){return null}}async function save(){try{localStorage.setItem(STORE,JSON.stringify(state))}catch(e){}}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function page(x){app.innerHTML=`<div class="screen"><div class="panel">${x}</div></div>`}function stars(id){return state.chapters[id]?.stars||0}
function start(){page(`<div class="title">WONDERS<br>WORD QUEST</div><div class="subtitle">A 16-BIT ENGLISH RPG ADVENTURE</div><input id="name" class="input" placeholder="ENTER YOUR NAME" maxlength="16"><div class="choices"><button class="choice" onclick="gender='boy'">👦 BOY</button><button class="choice" onclick="gender='girl'">👧 GIRL</button></div><div class="center badge">Choose your hero</div><button class="btn gold" onclick="create()">START ADVENTURE ▶</button>`);window.gender="boy"}
async function create(){let n=document.getElementById("name").value.trim();if(!n)return alert("請輸入名字");state=blank();state.name=n;state.gender=gender;await save();map()}
function menu(){page(`<div class="title">WONDERS WORD QUEST</div><div class="subtitle">YOUR WORD QUEST BEGINS!</div><div class="center badge">👤 ${esc(state.name)}　${state.gender==="boy"?"👦":"👧"}　SCORE ${state.score}</div><button class="btn" onclick="map()">🗺️ WORLD MAP</button><button class="btn" onclick="review()">🎯 REVIEW QUEST</button><button class="btn" onclick="book()">📖 MY WORD BOOK</button><button class="btn" onclick="achievements()">🏆 ACHIEVEMENTS</button>`)}
function map(){let x=data.chapters.map(c=>{let lock=c.id>state.unlocked;return `<button class="chapter ${lock?"locked":""}" ${lock?"disabled":`onclick="chapterMenu(${c.id})"`}><h3>${c.code}</h3>${c.title}<div class="stars">${"★".repeat(stars(c.id))}${"☆".repeat(3-stars(c.id))}</div><div class="small">${lock?"🔒 LOCKED":`${c.words.length} WORDS · ${state.chapters[c.id]?.complete?"✓ COMPLETE":"READY"}`}</div></button>`}).join("");page(`<div class="topbar"><button class="btn" style="width:auto;margin:0" onclick="menu()">← MENU</button><span class="badge">SCORE ${state.score}</span></div><div class="title" style="font-size:42px">🗺️ WONDERS WORLD</div><div class="map">${x}</div>`)}
function chapterMenu(id){chapter=data.chapters[id-1];page(`<div class="topbar"><button class="btn" style="width:auto;margin:0" onclick="map()">← MAP</button><span class="stars">${"★".repeat(stars(id))}${"☆".repeat(3-stars(id))}</span></div><div class="title" style="font-size:36px">${chapter.code}</div><div class="subtitle">${chapter.title}</div><button class="btn gold" onclick="play(${id},'mixed')">▶ PLAY QUEST</button><button class="btn" onclick="play(${id},'review')">🔄 REPLAY / PRACTICE</button><div class="wordgrid">${chapter.words.map(x=>`<div class="word"><b>${esc(x.w)}</b><br><span class="small">${esc(x.m)}</span><br>${"⭐".repeat(state.mastery[x.w]||0)}</div>`).join("")}</div>`)}
function play(id,m){chapter=data.chapters[id-1];mode=m;q=0;next()}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}function pool(){let p=chapter.words;return mode==="review"?p.filter(x=>(state.mastery[x.w]||0)<3).concat(p.filter(x=>(state.mastery[x.w]||0)>=3).slice(0,3)):p}
function choices(item){let opts=shuffle([item,...shuffle(chapter.words.filter(x=>x.w!==item.w)).slice(0,3)]);return `<div class="choices">${opts.map(o=>`<button class="choice" onclick="answer('${encodeURIComponent(o.w)}','${encodeURIComponent(item.w)}')">${esc(o.w)}</button>`).join("")}</div>`}
function next(){clearInterval(timer);locked=false;let p=pool();if(q>=Math.min(7,p.length)){finish();return}let item=p[q],m=modes[(q+chapter.id)%modes.length],body;if(m==="SPELL IT")body=`<div class="question">🔤 SPELL IT</div><div class="subtitle">${esc(item.m)}</div><input id="typed" class="input" placeholder="Type the English word"><button class="btn gold" onclick="typed('${encodeURIComponent(item.w)}')">SUBMIT</button>`;else if(m==="SCRAMBLE")body=`<div class="question">🧩 ${shuffle(item.w.split("")).join(" · ")}</div><div class="subtitle">${esc(item.m)}</div>${choices(item)}`;else if(m==="PICTURE MATCH")body=`<div class="question">🖼️ PICTURE MATCH</div><div class="subtitle">Choose the word for: ${esc(item.m)}</div>${choices(item)}`;else body=`<div class="question">${m==="SPEED CHALLENGE"?"⚡":"🎯"} ${m}</div><div class="subtitle">${esc(item.m)}</div>${choices(item)}`;page(`<div class="topbar"><button class="btn" style="width:auto;margin:0" onclick="chapterMenu(${chapter.id})">✕ EXIT</button><span class="badge">${q+1}/7</span><span class="timer" id="timer">30</span></div><div class="progress"><i style="width:${q/7*100}%"></i></div>${body}`);let left=30;timer=setInterval(()=>{left--;let e=document.getElementById("timer");if(e)e.textContent=left;if(left<=0){clearInterval(timer);wrong(item,true)}},1000)}
function typed(ans){if(locked)return;let v=document.getElementById("typed").value.trim().toLowerCase();v===decodeURIComponent(ans).toLowerCase()?correct(decodeURIComponent(ans)):wrong({w:decodeURIComponent(ans),m:""},false)}
function answer(a,b){if(locked)return;decodeURIComponent(a)===decodeURIComponent(b)?correct(decodeURIComponent(b)):wrong({w:decodeURIComponent(b),m:""},false)}
function correct(w){locked=true;clearInterval(timer);state.score+=100;state.mastery[w]=Math.min(3,(state.mastery[w]||0)+1);save();page(`<div class="center"><div class="title">✓</div><div class="question">CORRECT!</div><div class="subtitle">${esc(w)}</div><button class="btn gold" onclick="q++;next()">CONTINUE ▶</button></div>`)}
function wrong(item,timeout){if(locked)return;locked=true;clearInterval(timer);page(`<div class="center"><div class="title">✕</div><div class="question">${timeout?"TIME UP!":"TRY AGAIN!"}</div><div class="subtitle">${esc(item.w)}</div><button class="btn" onclick="q++;next()">CONTINUE ▶</button></div>`)}
function finish(){let mastered=chapter.words.filter(x=>(state.mastery[x.w]||0)>=3).length;let s=mastered>=5?3:mastered>=2?2:1;state.chapters[chapter.id]={complete:true,stars:Math.max(stars(chapter.id),s)};if(chapter.id===state.unlocked&&state.unlocked<data.chapters.length)state.unlocked++;state.score+=250;save();page(`<div class="center"><div class="title" style="font-size:46px">QUEST CLEAR!</div><div class="question">${"⭐".repeat(s)}${"☆".repeat(3-s)}</div><div class="subtitle">Words mastered: ${mastered}/${Math.min(7,chapter.words.length)}<br>你可以隨時 Replay 這一章。</div><button class="btn gold" onclick="chapterMenu(${chapter.id})">🔄 PLAY AGAIN</button><button class="btn" onclick="map()">🗺️ WORLD MAP</button></div>`)}
function review(){let weak=[];data.chapters.forEach(c=>c.words.forEach(x=>{if((state.mastery[x.w]||0)<3)weak.push([x,c])}));page(`<div class="topbar"><button class="btn" style="width:auto;margin:0" onclick="menu()">← MENU</button></div><div class="title" style="font-size:38px">🎯 REVIEW QUEST</div><div class="subtitle">系統會優先找出還沒三星的單字。</div>${weak.slice(0,20).map(([x,c])=>`<div class="review-card"><b>${esc(x.w)}</b> — ${esc(x.m)}<br><span class="small">${c.code} · ${"⭐".repeat(state.mastery[x.w]||0)}${"☆".repeat(3-(state.mastery[x.w]||0))}</span></div>`).join("")}${weak.length?`<button class="btn gold" onclick="globalReview()">▶ START REVIEW</button>`:"<div class='center'>🎉 目前單字都已達三星！</div>"}`)}
function globalReview(){let all=[];data.chapters.forEach(c=>c.words.forEach(x=>{if((state.mastery[x.w]||0)<3)all.push({...x})}));if(!all.length)return;chapter={id:0,code:"REVIEW",title:"Mixed Review",words:shuffle(all).slice(0,7)};mode="review";q=0;next()}
function book(){page(`<div class="topbar"><button class="btn" style="width:auto;margin:0" onclick="menu()">← MENU</button></div><div class="title" style="font-size:38px">📖 MY WORD BOOK</div>${data.chapters.map(c=>`<h3>${c.code} · ${c.title}</h3><div class="wordgrid">${c.words.map(x=>`<div class="word"><b>${esc(x.w)}</b><br>${esc(x.m)}<br>${"⭐".repeat(state.mastery[x.w]||0)}${"☆".repeat(3-(state.mastery[x.w]||0))}</div>`).join("")}</div>`).join("")}`)}
function achievements(){let n=Object.values(state.chapters).filter(x=>x.complete).length,m=Object.values(state.mastery).filter(x=>x>=3).length;page(`<div class="topbar"><button class="btn" style="width:auto;margin:0" onclick="menu()">← MENU</button></div><div class="title" style="font-size:38px">🏆 ACHIEVEMENTS</div><div class="review-card">🗺️ WORD EXPLORER — ${n} Chapters cleared</div><div class="review-card">📖 WORD MASTER — ${m} words mastered</div><div class="review-card">⭐ THREE-STAR HERO — ${Object.values(state.chapters).filter(x=>x.stars>=3).length} Chapters at 3 stars</div>`)}
(async()=>{data=await fetch("data.json").then(r=>r.json());state=await getSave()||blank();state.name?menu():start()})()
